### ISSUE TITLE
Almost Works

### ISSUE THREAD

**Issue by Krutonium** [CanadianCommander/CGNM-2250-SHW-Root#1]
Okay so this *almost* works on my Modem, but it runs into an issue where as soon as I connect, i'm disconnected. 
```
[krutonium@Arch-MSI ~]$ netcat 192.168.0.1 1234
/bin/sh: can't access tty; job control turned off


BusyBox v1.22.1 (2018-10-10 10:31:40 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

# [krutonium@Arch-MSI ~]$                    
```
Any thoughts about what may be going wrong here?

**Comment by ochen1** [comment]
You get disconnected? I also see this error but I still get access to the root shell.

**Comment by Krutonium** [comment]
Yep, I get disconnected.

**Comment by BenjaminBenetti** [comment]
That moment when you realize someone has posted on a repo you made... that never happens :laughing:. Unfortunately I no longer have this router.  Seeing as this post is so, old I'll close this issue.
